[theme]
primaryColor="#14b8a6"  # Teal (calm, modern)
backgroundColor="#0a0f19"  # Deep Navy (dark and sleek)
secondaryBackgroundColor="#1c2b3a"  # Muted Blue-Gray (subtle contrast)
textColor="#e0e7ff"  # Soft Lavender-White (easy on the eyes)
